ansible-user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.sanjeethadevops.online
REDIS_HOST: redis-dev.sanjeethadevops.online
USER_HOST: user-dev.sanjeethadevops.online
CATALOGUE_HOST: catalogue-dev.sanjeethadevops.online
CART_HOST: cart-dev.sanjeethadevops.online
MYSQL_HOST: mysql-dev.sanjeethadevops.online
SHIPPING_HOST: shipping-dev.sanjeethadevops.online
RABBITMQ_HOST: rabbitmq-dev.sanjeethadevops.online
PAYMENT_HOST: payment-dev.sanjeethadevops.online