- name: msg1
  ansible.builtin.debug:
    msg: "Hi from MSG-1"

- name: set os fact
  ansible.builtin.set_fact:
   os: "debian"  


- name: msg2
  ansible.builtin.debug:
    msg: "Hi from MSG-2"

- name: msg3
  ansible.builtin.debug:
    msg: "Hi from MSG-3"        


